### ISSUE TITLE
Introduce 5,000 bucket

### ISSUE THREAD

**Issue by rauchg** [zakird/crux-top-lists#1]
Thanks for the super handy project!

The only gap I ran into: I couldn't find the `,5000` entries in the CSV. This bucket was recently introduced I believe by the CrUX report:

https://developer.chrome.com/docs/crux/release-notes/#202210

**Comment by tja** [comment]
Hi @rauchg .. If you're still looking for this, my project https://github.com/crissyfield/crux-dumps might be interesting for you.

**Comment by zakird** [comment]
I have confirmed that these are present in the downloads once Chrome added them.

**Comment by ldsys** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
danielgjackson, @grahame, @sharukhhasan, @goby, @fettliu, @yuhui-zheng, @shanipribadi, @rbryan, @wansishuang, @usc-m, @burnflare, @raymondwung, @ASD0x41, @jake-low, @livingstaccato, @AlfredoPrades, @PyrekP, @bonedaddy, @Theldus, @tangnotes, @Quantum-Tunneling, @helje5, @TheCams, @lday0321, @abrahamtrevino, @myszon, @tavakyan, @expvictordamian, @rxgx, @TBK, @Mati365, @dewaffled, @javakf, @howkj1, @denis-yermakov, @alexw91, @RockRunner007, @gosoxharp, @bryantcutler, @dayanruben, @luoshenzhi, @jokeyrhyme, @fukamachi, @stfnm, @aninggo, @aug2uag, @Kazuma, @trietptm, @abl, @mcroydon
