### ISSUE TITLE
URL category

### ISSUE THREAD

**Issue by amreesh** [zakird/crux-top-lists#2]
Do you know if it's possible to have the URL category as per:
https://support.google.com/a/answer/13306955?hl=en

**Comment by zakird** [comment]
It doesn't look like this data is included in CrUX: https://developer.chrome.com/docs/crux/api/#record. I'd follow up with the Chrome folks if you'd like to see it. I'm happy to include it in our dumps if Google adds it — seems like something that would incredibly useful to everyone.
