### ISSUE TITLE
Tallied List

### ISSUE THREAD

**Issue by erifetavoke** [zakird/crux-top-lists#6]
How possible is it to get a tallying list of the owners of the websites along side or in a different csv file. It'll be very much appreciated.

**Comment by zakird** [comment]
I don't think that this falls within scope of this project, which is meant to provide simple top lists. Most ownership questions will be answered using third-party WHOIS data. If there are other fields you want to extract out of CrUX, these can also queried out using BigQuery directly from Google Chrome.
